In [5]:
# 範例2 (融合版)抓網站資料應用 pandas 
###

import requests
import pandas as pd

# 設定time為獲取中文姓名100筆的倍數。time=3，就是300筆的意思。
times = 1
cnames = []
for x in range(times):
    url = 'http://www.richyli.com/name/index.asp'
    r = requests.get(url)
    r.encoding = 'big5'
    
    # 將網頁中的資料以分行的方式存成文字檔
    result = r.text.splitlines()
    
    # 114是中文姓名開始的列，找到最後一個「、」，設定成為字串的切片位置。
    char_index = result[114].rfind("、")
    temp = result[114][:char_index]
    
    # 將temp的100筆姓名新增到cnames中
    cnames.append(temp)

# 將每100筆姓名的list加一個「、」，再組合成字串存到my_names中
my_names = "、".join(str(x) for x in cnames)
print(my_names)

###

import requests
def getNames(num):
    times = 1
    cnames = []
    for x in range(times):
        url = 'http://www.richyli.com/name/index.asp'
        r = requests.get(url)
        r.encoding = 'big5'
        
        # 將網頁中的資料以分行的方式存成文字檔
        result = r.text.splitlines()
        
        # 114是中文姓名開始的列，找到最後一個「、」，設定成為字串的切片位置。
        char_index = result[114].rfind("、")
        temp = result[114][:char_index]
        
        # 將temp的100筆姓名新增到cnames中
        cnames.append(temp)
    print(type(cnames[0]))
    names = cnames[0].split('、')
    return names[:num]

names = getNames(100)

張威廷、謝宗儒、林柏名、方怡君、柳筱亨、潘俐雲、吳羿純、周佳蓉、陳子揚、李文欣、曾綺華、劉淑芳、謝依羽、酈威貞、侯建平、鄧姿婷、陳蘭剛、張祐岑、趙家慧、張晉芝、陳淑貞、李妙漢、金青豪、黃志隆、溫紹美、袁明輝、邱方沛、吳淑真、林均丹、謝欣妤、李依美、鄧智仁、林佩儒、楊冠良、賴怡昀、林佩祥、袁善佐、黃志鴻、方怡君、李剛以、林則光、郭怡婷、王坤揚、李民青、李盈甄、朱有勇、陳俊臻、林育紹、彭佩儒、溫筱芸、陳姵松、張侑財、謝詩涵、李建貴、王思婷、謝美惠、林育娥、曾欣怡、許偉銘、馮璇豐、陳瓊茹、陳郁廷、李雅晴、游敬駿、林家榮、胡淑娟、胡怡芬、蔡孟哲、游揚綠、蔡琳桓、李劭以、黃志文、連雯嬌、連光鴻、李明夫、黃苡玉、林雅文、陳秀琳、簡淑玲、施翔筠、王婉君、陳采儀、吳鳳南、吳成韋、柳行蕙、鄭秋燕、林仲陽、陳淑真、黃欣儀、楊智超、林庭城、奚丞隆、賴卉青、張淑君、黃建純、鄭雅念、蔣良元、謝亮雯、王苡瑩、權宜靜
<class 'str'>

In [7]:
##-1

import numpy as np
import pandas as pd

n2 = np.random.randint(59,100,size=(11,5))
dataFrame = pd.DataFrame(data=n2,
             index=names[:11],
             columns=["國文","英文","數學","地理","歷史"]
             )
dataFrame

     國文  英文  數學  地理  歷史
王建臻  92  73  79  94  89
林孟容  90  63  63  63  92
方筱雯  64  82  87  78  85
吳雅惠  93  75  72  95  90
黃璇隆  59  62  90  73  89
童又謙  60  85  60  86  65
楊鎮福  72  71  77  79  97
林冠琬  82  97  67  65  81
劉政能  83  98  78  68  98
許展昇  83  84  65  73  75
何筱涵  99  88  64  86  59

In [8]:
total = dataFrame["數學"]+ dataFrame["地理"]+ dataFrame["歷史"]+ dataFrame["英文"]+ dataFrame["國文"]
dataFrame["TOTAL"] = total
dataFrame

     國文  英文  數學  地理  歷史  TOTAL
王建臻  92  73  79  94  89    427
林孟容  90  63  63  63  92    371
方筱雯  64  82  87  78  85    396
吳雅惠  93  75  72  95  90    425
黃璇隆  59  62  90  73  89    373
童又謙  60  85  60  86  65    356
楊鎮福  72  71  77  79  97    396
林冠琬  82  97  67  65  81    392
劉政能  83  98  78  68  98    425
許展昇  83  84  65  73  75    380
何筱涵  99  88  64  86  59    396

In [9]:
# 範例2 v2 
###

import requests
import pandas as pd

# 設定time為獲取中文姓名100筆的倍數。time=3，就是300筆的意思。
times = 1
cnames = []
for x in range(times):
    url = 'http://www.richyli.com/name/index.asp'
    r = requests.get(url)
    r.encoding = 'big5'
    
    # 將網頁中的資料以分行的方式存成文字檔
    result = r.text.splitlines()
    
    # 114是中文姓名開始的列，找到最後一個「、」，設定成為字串的切片位置。
    char_index = result[114].rfind("、")
    temp = result[114][:char_index]
    
    # 將temp的100筆姓名新增到cnames中
    cnames.append(temp)

# 將每100筆姓名的list加一個「、」，再組合成字串存到my_names中
my_names = "、".join(str(x) for x in cnames)
print(my_names)

###

import requests
def getNames(num):
    times = 1
    cnames = []
    for x in range(times):
        url = 'http://www.richyli.com/name/index.asp'
        r = requests.get(url)
        r.encoding = 'big5'
        
        # 將網頁中的資料以分行的方式存成文字檔
        result = r.text.splitlines()
        
        # 114是中文姓名開始的列，找到最後一個「、」，設定成為字串的切片位置。
        char_index = result[114].rfind("、")
        temp = result[114][:char_index]
        
        # 將temp的100筆姓名新增到cnames中
        cnames.append(temp)
   
   
names = getNames()

柳璇雨、徐容峰、賴俊韋、朱孟勳、林威弘、胡年、李歡發、謝依凌、賴有易、馬白凌、戴耿玲、洪國喬、張文彬、李善元、陳季雲、蔡倫玲、陳秋霞、李皇韻、駱淑貞、陳豪琇、葉意恬、劉石昆、王佩芳、黃嘉慧、陳莉丞、林嘉孝、周以中、蔡建宇、謝翰貞、王淑如、李淑媛、謝景漢、溫靜怡、陳冠廷、吳建廷、鄧珮君、陳佩良、魏欣儀、楊佩怡、陳冠宇、林協揚、魏重倫、王淑君、蘇岱愛、劉翔弘、陳雅雯、張佳卿、董孝琪、賴怡珊、吳明湖、陳睿念、陳國堯、姜婉君、吳春婷、沈靜怡、林聖揚、吳聖凱、蔡方慧、連宜君、吳蓉清、陳宜臻、陳奕迪、程靜宜、劉智堯、林國成、劉伊心、唐喜茜、高彥宇、貢晴寧、林士瑋、蔡佳雯、陳馨亦、林牧州、黃致琪、吳琬興、林鈺婷、張真玉、鄧淑玲、杜嘉雯、林岱年、劉志宇、黃琬婷、朱雅文、張秉哲、張婕妤、盧恩雪、余先芃、游義茜、黃淑來、林柏亨、林燕倩、王雅茹、吳家慶、楊憲瑋、江佳宏、何青蓮、林函君、黃雅霖、林明杰、楊佳容

TypeError: getNames() missing 1 required positional argument: 'num'